import type { QedConfig, RunRecord, RunSnapshot } from "../types";

const capturedAt = "2026-07-16T20:00:00Z";
const hash = "1f2e3d4c5b6a7980112233445566778899aabbccddeeff001122334455667788";
const provenance = {
  source: "codex",
  source_id: "thread-prover-1",
  model: "gpt-5.6-sol",
  runtime_version: "openai-codex/1.0",
  prompt_version: "proof/v1",
  captured_at: capturedAt,
};

const config: QedConfig = {
  schema_version: 1,
  model: "gpt-5.6-sol",
  effort: "high",
  backend: "auto",
  parallelism: { runs: 1, proof_candidates: 4, verifiers: 2, proactive_multi_agent: true },
  budgets: {
    run_seconds: 7200,
    stage_seconds: 1800,
    max_tokens: 250000,
    proof_attempts: 8,
    plan_revisions: 2,
    strategy_rewrites: 2,
    turn_retries: 2,
  },
  search: { enabled: true, allowed_roles: ["literature", "citation"], max_queries_per_stage: 20 },
  sandbox: {
    literature: "read-only",
    planner: "read-only",
    prover: "read-only",
    verifier: "read-only",
    adjudicator: "read-only",
    approval: "never",
  },
};

export const runRecord: RunRecord = {
  id: "finite-groups-2026-07-16",
  schema_version: 1,
  status: "completed",
  stage: "complete",
  config,
  config_sha256: hash,
  input_sha256: hash,
  provenance,
  provenance_sha256: hash,
  runtime_version: provenance.runtime_version,
  cancellation_requested: false,
  resumable: false,
  resume_count: 0,
  execution_version: 1,
  proof_attempt_count: 1,
  plan_revision_count: 0,
  strategy_rewrite_count: 0,
  created_at: capturedAt,
  updated_at: "2026-07-16T20:18:00Z",
};

const reports = (["structural", "detailed", "citation"] as const).map((kind, index) => ({
  id: `verification-${kind}`,
  run_id: runRecord.id,
  candidate_id: "candidate-1",
  thread_id: `thread-verifier-${index + 1}`,
  kind,
  schema_version: 1,
  report: {
    schema_version: 1 as const,
    id: `report-${kind}`,
    candidate_id: "candidate-1",
    candidate_sha256: hash,
    kind,
    checks: [
      {
        id: `check-${kind}`,
        category: kind,
        status: "pass" as const,
        summary: `${kind} verification passed against the frozen proof.`,
        proof_spans: ["Lemma 2"],
        evidence_ids: kind === "citation" ? ["evidence-1"] : [],
      },
    ],
    findings: [],
    verifier_thread_id: `thread-verifier-${index + 1}`,
    verifier_external_thread_id: `codex-thread-${index + 1}`,
    provenance: { ...provenance, source_id: `thread-verifier-${index + 1}`, prompt_version: `${kind}/v1` },
    created_at: `2026-07-16T20:${10 + index}:00Z`,
    verdict: "pass" as const,
  },
  report_sha256: hash,
  candidate_sha256: hash,
  provenance: { ...provenance, source_id: `thread-verifier-${index + 1}` },
  provenance_sha256: hash,
  created_at: `2026-07-16T20:${10 + index}:00Z`,
}));

export const completedSnapshot: RunSnapshot = {
  run: runRecord,
  run_input: {
    schema_version: 1,
    problem: "Prove that every finite subgroup of the multiplicative group of a field is cyclic.",
    prove_guidance: "Use the root bound for polynomials over a field.",
    verification_rules: ["Check the maximal-order argument.", "Verify every cited result."],
  },
  events: [
    {
      schema_version: 1,
      run_id: runRecord.id,
      seq: 8,
      event_type: "candidate.sealed",
      stage: "proving",
      payload: { candidate_id: "candidate-1", candidate_sha256: hash },
      payload_sha256: hash,
      created_at: "2026-07-16T20:08:00Z",
    },
    {
      schema_version: 1,
      run_id: runRecord.id,
      seq: 12,
      event_type: "candidate.decision_recorded",
      stage: "adjudication",
      payload: { candidate_id: "candidate-1", passed: true },
      payload_sha256: hash,
      created_at: "2026-07-16T20:15:00Z",
    },
  ],
  stage_outputs: [],
  threads: [
    {
      id: "thread-prover-1",
      run_id: runRecord.id,
      role: "prover",
      parent_thread_id: null,
      external_thread_id: "codex-prover-1",
      model: "gpt-5.6-sol",
      status: "completed",
      schema_version: 1,
      provenance,
      provenance_sha256: hash,
      created_at: "2026-07-16T20:06:00Z",
      updated_at: "2026-07-16T20:08:00Z",
    },
    ...reports.map((record, index) => ({
      id: record.thread_id,
      run_id: runRecord.id,
      role: "verifier" as const,
      parent_thread_id: null,
      external_thread_id: record.report.verifier_external_thread_id,
      model: "gpt-5.6-sol",
      status: "completed" as const,
      schema_version: 1,
      provenance: record.provenance,
      provenance_sha256: hash,
      created_at: `2026-07-16T20:${9 + index}:00Z`,
      updated_at: `2026-07-16T20:${10 + index}:00Z`,
    })),
  ],
  candidates: [
    {
      id: "candidate-1",
      run_id: runRecord.id,
      thread_id: "thread-prover-1",
      plan_id: "plan-1",
      attempt: 1,
      schema_version: 1,
      candidate: {
        schema_version: 1,
        id: "candidate-1",
        run_id: runRecord.id,
        plan_id: "plan-1",
        attempt: 1,
        proof: "Every finite subgroup of the multiplicative group is abelian. Choose an element of maximal order and apply the root bound to show every element lies in the cyclic subgroup it generates.",
        proof_sha256: hash,
        evidence_ids: ["evidence-1"],
        deviations: [],
        provenance,
        created_at: "2026-07-16T20:08:00Z",
      },
      candidate_sha256: hash,
      proof_sha256: hash,
      provenance,
      provenance_sha256: hash,
      sealed_at: "2026-07-16T20:08:00Z",
      created_at: "2026-07-16T20:08:00Z",
      updated_at: "2026-07-16T20:08:00Z",
    },
  ],
  verifications: reports,
  artifacts: [
    {
      id: "artifact-proof",
      run_id: runRecord.id,
      kind: "proof",
      relative_path: "finite-groups/proof.md",
      media_type: "text/markdown",
      sha256: hash,
      size_bytes: 2480,
      schema_version: 1,
      provenance,
      provenance_sha256: hash,
      created_at: "2026-07-16T20:17:00Z",
    },
  ],
  execution_segments: [],
  evidence: [
    {
      schema_version: 1,
      id: "evidence-1",
      kind: "theorem",
      title: "Classical group result",
      content: "A polynomial of degree n over a field has at most n roots.",
      content_sha256: hash,
      provenance: { ...provenance, source_id: "doi:10.0000/example", prompt_version: "literature/v1" },
      source_uri: "https://example.test/paper",
      citation: "Classical Algebra, Theorem 4.2",
    },
  ],
  plans: [
    {
      schema_version: 1,
      id: "plan-1",
      problem_sha256: hash,
      strategy: "Compare element orders with the root bound.",
      steps: [
        {
          id: "step-1",
          statement: "Choose an element of maximal order.",
          rationale: "Finiteness guarantees a maximum.",
          success_criteria: ["The chosen order dominates every element order."],
          dependencies: [],
          evidence_ids: ["evidence-1"],
          key_step: true,
        },
      ],
      provenance,
      created_at: "2026-07-16T20:05:00Z",
    },
  ],
  adjudications: [
    {
      schema_version: 1,
      id: "adjudication-1",
      candidate_id: "candidate-1",
      report_ids: reports.map((record) => record.report.id),
      outcome: "accept",
      rationale: "All independent required reports pass.",
      provenance: { ...provenance, source_id: "thread-adjudicator-1" },
      created_at: "2026-07-16T20:15:00Z",
    },
  ],
  decisions: [
    {
      schema_version: 1,
      candidate_id: "candidate-1",
      candidate_sha256: hash,
      passed: true,
      required_kinds: ["structural", "detailed", "citation"],
      report_ids: reports.map((record) => record.report.id),
      reasons: [],
    },
  ],
};
